version: "3.4"

services:
  pomodorobackend:
    image: pomodorobackend
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - pomodoros.env
    ports:
      - 3000:3000
